Time is Weird
twizzler-operating-system/rfcs pull request #3
Opened 2022-06-07 17:03 UTC by PandaZ3D

A draft of a set of abstractions for user space and the kernel.

2022-06-10 21:52 UTC, gvnn3 requested changes

2022-06-10 21:52 UTC, gvnn3 commented on text/0000-time.md
> +```rust
Please specify the meanings of each of these fields.  I suspect some are time (nano/femto/pico seconds) and one is drift in parts per million.  Check out this page fore more on this: http://www.ntp.org/ntpfaq/NTP-s-sw-clocks-quality.htm

2022-06-10 23:52 UTC, dbittman commented on text/0000-time.md
> +    id: u64 // leads us to the clock source
I'd like this to be a type, something like
`#[repr(transparent)] struct ClockId(u64)`

2022-06-10 23:53 UTC, dbittman commented on text/0000-time.md
> +    Unknown
Place Unknown as first element.

2022-06-10 23:54 UTC, dbittman commented on text/0000-time.md
> +fn sys_read_clock_info(clock: ClockUsage, clock_id: u64, flags: ReadClockFlags) -> Result<ClockInfo, ReadClockError>
As we discussed on wednesday, I'd like to see this changed to an API that doesn't admit erroneous combinations of arguments.

2022-06-10 23:55 UTC, dbittman requested changes
See comments. I'd also suggest removing references to time adjustment and specifying that a future RFC will define the API to adjust clocks.

2022-06-25 02:54 UTC, PandaZ3D commented
Thanks for the suggestions everyone. I have incorporated feedback from our conversations. 

The only new thing is the introduction of `TimeSpan` meant to represent some point in time. It is a timestamp that much like `Duration`/`timespec`, except unlike legacy abstractions, is designed to support high precision time sources. `TimeSpan` uses two 64-bit integers encapsulated behind `Seconds` and `FemtoSeconds`.

2022-06-28 01:04 UTC, dbittman commented
Is the rationale that the TimeSpan is more future-proof in that is supports femtosecond resolution, and that the other precision information is given in femtoseconds anyway, so it typechecks better than using nanoseconds?

That's fine by me. We'll, of course, need to impl From<TimeSpan> for Duration (or, if that's not possible, impl Into<Duration> for TimeSpan), since the Rust std library will still use Duration.

2022-06-28 01:06 UTC, dbittman approved these changes
Looks good!

2022-06-28 19:21 UTC, PandaZ3D commented
Yes. Femtosecond clock hardware exists, but is pricey. However, it is reasonable to assume that modern hardware could have picosecond resolution or precision. If we feel that femtoseconds is too fine grained, we can go with picoseconds as well. Nanoseconds is too coarse grained which is a nonstarter.

2022-06-29 18:34 UTC, merged